import{a as b,S,i as a}from"./assets/vendor-DQvd0HNi.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function p(r,s){const e="https://pixabay.com",i="/api/",t=new URLSearchParams({key:"55046527-8fc3f9f8db0162eee6eb185b5",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}),o=e+i+"?"+t;return(await b.get(o)).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more-button"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250});function g(r){const s=r.map(e=>`
        <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </li>
        `).join("");m.insertAdjacentHTML("beforeend",s),q.refresh()}function v(){m.innerHTML=""}function L(){h.style.display="block"}function d(){h.style.display="none"}function R(){y.classList.remove("hide")}function u(){y.classList.add("hide")}const w={form:document.querySelector(".form"),loadMoreBtn:document.querySelector(".load-more-button")};let l="",n=1,f=0;w.form.addEventListener("submit",async r=>{if(r.preventDefault(),l=new FormData(r.target).get("search-text").trim(),l===""){a.error({message:"Please enter a search query!",position:"topRight"});return}n=1,v(),u(),L();try{const e=await p(l,n);if(f=e.totalHits,e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),e.hits.length<15||n*15>=f?u():R()}catch(e){d(),a.error({message:"Oops, something went wrong!",position:"topRight"}),console.log(e)}finally{d()}});w.loadMoreBtn.addEventListener("click",async()=>{n+=1,L();try{const r=await p(l,n);g(r.hits),n*15>=f&&(u(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const s=document.querySelector(".gallery-item");if(s){const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(r){a.error({message:"Oops, something went wrong!",position:"topRight"}),console.log(r)}finally{d()}});
//# sourceMappingURL=index.js.map
